name: CI
on: 
  pull_request:
  push:
    branches:
      - main
      - add_GHA_based_CI
        # TODO Remove line above and uncomment line below
        #  workflow_dispatch:

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build SDist
        run: pipx run build --sdist

      - name: Upload SDist
        uses: actions/upload-artifact@v4
        with:
          name: example
          path: dist/*.tar.gz

            #  build_wheels:
            #    name: Wheel on ${{ matrix.os }}
            #    runs-on: ${{ matrix.os }}
            #    strategy:
            #      fail-fast: false
            #      matrix:
            #        os: [ubuntu-latest, windows-latest, macos-latest]
            #    steps:
            #      - uses: actions/checkout@v4
            #
            #      - name: Build wheels
            #        uses: pypa/cibuildwheel@v2.18.1
            #
            #      - name: Upload wheels
            #        uses: actions/upload-artifact@v4
            #        with:
            #          name: cibw-wheel-${{ matrix.os }}
            #          path: wheelhouse/*.whl

  # --- Copied from https://cibuildwheel.pypa.io/en/stable/setup/#configure-a-ci-service --- #
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
       
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1
       # env:
       #   CIBW_SOME_OPTION: value
       #    ...
       # with:
       #   package-dir: .
       #   output-dir: wheelhouse
       #   config-file: "{package}/pyproject.toml"
       
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
