name: CI
on: 
  pull_request:
  push:
    branches:
      - main
      - add_GHA_based_CI

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: pypa/build@v1.2.1
        name: Build SDist

      - uses: actions/upload-artifact@v4
        with:
          name: example
          path: dist/*.tar.gz

  build_wheels:
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
       
      - uses: pypa/build@v1.2.1
        name: Build Wheel

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: example-wheel-${{ matrix.os }}
          path: dist/*.whl
