name: CI
on: 
  pull_request:
  push:
    branches:
      - main
      - add_GHA_based_CI

jobs:
  install_build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          allow-prereleases: true

      - name: Install build module on ${{ matrix.os }}
        run: python -m pip install build

  make_sdist:
    needs: install_build
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Build SDist
        run: python -m build .


      - uses: actions/upload-artifact@v4
        with:
          name: example
          path: dist/*.tar.gz

  build_wheels:
    needs: install_build
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
       
      - name: Build Wheel
        run: python -m build .

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: example-wheel-${{ matrix.os }}
          path: dist/*.whl
