name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - cibuildwheel_based_CI
        # TODO Remove line above and uncomment line below
        #  workflow_dispatch:

jobs:
  # TODO Uncomment when build_wheels starts working
  #make_sdist:
    #name: Make SDist
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v4

      #- name: Build SDist
        #run: pipx run build --sdist

      #- name: Upload SDist
        #uses: actions/upload-artifact@v4
        #with:
          #name: example
          #path: dist/*.tar.gz

  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1
        with:
          config-file: "pyproject.toml"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheel-${{ matrix.os }}
          path: wheelhouse/*.whl
